amp_opt_level: 1
assume_yes: false
base_lr: 0.01
batch_size: 32
checkpoint: null
config: ./config/autsl-skeleton-evaluation/val_joint_tta.yaml
debug: false
device:
- 0
eval_interval: 1
eval_start: 1
feeder: feeders.feeder.Feeder
forward_batch_size: 16
half: false
ignore_weights: []
log_interval: 100
model: model.msg3d.Model
model_args:
  graph: graph.autsl_joints.AdjMatrixGraph
  num_class: 226
  num_g3d_scales: 8
  num_gcn_scales: 8
  num_person: 1
  num_point: 55
model_saved_name: ''
nesterov: false
num_epoch: 80
num_worker: 64
optimizer: SGD
optimizer_states: null
phase: test
print_log: true
save_interval: 1
save_score: true
seed: 67
show_topk:
- 1
- 5
start_epoch: 0
step:
- 45
- 55
test_batch_size: 32
test_feeder_args:
  data_path: ../data_autsl/autsl/val_data_joint.npy
  debug: false
  label_path: ../data_autsl/autsl/val_label.pkl
train_feeder_args: {}
tta:
- - false
  - 1
- - true
  - 1
- - false
  - 1.1
- - true
  - 1.1
- - false
  - 0.9
- - true
  - 0.9
weight_decay: 0.0005
weights: /home/temporal2/mvazquez/skeleton_action_recognition/MS-G3D/pretrained-models/autsl_eval/J1_T3.pt
work_dir: ./eval/autsl-evaluation/J1_T3
