# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ../data/autsl/val_data_joint.npy
  label_path: ../data/autsl/val_label.pkl
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 226
  num_point: 55
  num_person: 1
  num_gcn_scales: 8
  num_g3d_scales: 8
  graph: graph.autsl_joints.AdjMatrixGraph


# test
phase: test
device: 0
test_batch_size: 32
weights: /home/temporal2/mvazquez/skeleton_action_recognition/MS-G3D/pretrained-models/autsl_eval/joint/msg3d_joint_aug_drop_resize_tta_train1_weights-66-14454.pt

work_dir: ./eval/autsl-evaluation/folder_val_joint
save_score: True

tta : [
  [False,1],
  [True,1],
  [False,1.1],
  [True,1.1],
  [False,0.9],
  [True,0.9]
  ]